# Generated by Django 3.2.2 on 2021-05-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orangeFarmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('maturity_date', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orangeFarmers.orangefarmer')),
            ],
        ),
    ]
