# Generated by Django 3.2.2 on 2021-05-08 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oranges', '0002_auto_20210508_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='orange',
            name='supplier',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
