# Generated by Django 3.2.4 on 2021-06-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oranges', '0005_auto_20210509_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orange',
            name='hired',
        ),
    ]
