# Generated by Django 3.2.2 on 2021-05-08 18:40

import orangeFarmers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to=orangeFarmers.models.profile_path)),
            ],
        ),
    ]
